---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  wait: false
  path: apps/kube-system/metrics-server/app
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: home-ops-iot
    namespace: flux-system
