[env]
KUBECONFIG = '{{config_root}}/kubeconfig'
SOPS_AGE_KEY_FILE = '{{config_root}}/age.key'

[tools]
# Kubectl + Plugins
"kubectl" = "1.34.1"
"flux2" = "2.7.2"
"kustomize" = "latest"
"k9s" = "latest"
"helm" = "latest"
"helmfile" = "latest"

# Secret Encryption Stuff
"sops" = "latest"
"age" = "latest"

# Linters
"actionlint" = "latest"
"yamllint" = "latest"
"shellcheck" = "latest"
"yq" = "latest"
"jq" = "latest"

# Runtimes
python = "latest"
uv = "latest"

[tasks."encrypt"]
description = "Encrypt all sops files."
run = "bash ${MISE_PROJECT_ROOT}/.scripts/sops-encrypt-all.sh"

[tasks."decrypt"]
description = "Decrypt all sops files."
run = "bash ${MISE_PROJECT_ROOT}/.scripts/sops-decrypt-all.sh"

[tasks."lint"]
description = "Run all linters."
run = [
    "actionlint",
    "yamllint .",
    "shellcheck **/*.sh",
]