---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-mikrotik
spec:
  chartRef:
    kind: OCIRepository
    name: external-dns
  interval: 1h

  values:
    fullnameOverride: external-dns-mikrotik

    logLevel: info
    logFormat: text

    interval: 5s
    sources: ["ingress", "service", "crd"]
    registry: txt
    txtOwnerId: iot
    txtPrefix: k8s.iot.
    policy: sync
    triggerLoopOnEvent: true

    podAnnotations:
      secret.reloader.stakater.com/reload: mikrotik-credentials

    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/mirceanton/external-dns-provider-mikrotik
          tag: v1.4.24
        env:
          - name: LOG_FORMAT
            value: json
          - name: LOG_LEVEL
            value: debug

          - name: MIKROTIK_BASEURL
            valueFrom:
              secretKeyRef:
                name: mikrotik-credentials
                key: MIKROTIK_BASEURL
          - name: MIKROTIK_USERNAME
            valueFrom:
              secretKeyRef:
                name: mikrotik-credentials
                key: MIKROTIK_USERNAME
          - name: MIKROTIK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mikrotik-credentials
                key: MIKROTIK_PASSWORD
          - name: MIKROTIK_SKIP_TLS_VERIFY
            valueFrom:
              secretKeyRef:
                name: mikrotik-credentials
                key: MIKROTIK_SKIP_TLS_VERIFY

        livenessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
