apiVersion: v1
kind: Secret
metadata:
    name: mikrotik-credentials
stringData:
    MIKROTIK_USERNAME: ENC[AES256_GCM,data:eYhnhoJqIzxZCDnm,iv:QMeQ2lkJdo4oZekQB1nwT3noKXFpF6aGSPMq5Ml/9LM=,tag:fbwMcsUWEpI39j+trWIw/g==,type:str]
    MIKROTIK_PASSWORD: ENC[AES256_GCM,data:zGm/7m+YetYuBiYY,iv:ZNvORjT+9f7/XqnTrC+jalv4PWHmaNF6OOEin+zmQ/A=,tag:kD6cLHcOsiIOwYI2z0RdQg==,type:str]
    MIKROTIK_DEFAULT_TTL: ENC[AES256_GCM,data:n3TaVw==,iv:fRSIOoFu8+KLVG1//gk+JkakJnw4bS1LdplRg0/6T5g=,tag:c1+sycOhIUC1BqxmbATLTQ==,type:str]
    MIKROTIK_BASEURL: ENC[AES256_GCM,data:F/fRL42WfVvkybXUD7zsyQ==,iv:v8ZeCGvXiPbg3/IKMNZjUsS7mrmgJTxzqmdBgF4xDuI=,tag:vRcjlerEb17ZlAp9vCYo5w==,type:str]
    MIKROTIK_SKIP_TLS_VERIFY: ENC[AES256_GCM,data:SVkmww==,iv:FrpvVKREFIY0LOQJuh4WJP/7pBeKUfRryoSUxQoaVsU=,tag:wYYpgw7MheW7+qUEgEh9eA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zppxhaxerhqwyfmtw8n04k63yhq0h0ymdhaysslglhl2y6pl9cvshtchah
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoc0RMbmg2aEJyOHhLTDMx
            ZUZtcTJjc3Nvc1A0VVlaYUxoMjNHRStiTGtzClF4NlhJMmc5UDk1UkRqb1Rldy9v
            U05wYWtUN2g5MnRZSkhtV1FHZkNEY00KLS0tIFIwaVBERnd6cVZBa2llQmNqdi9Q
            L2tGcmV6WUNSNWxjcGl5a1Y4d2Rsd2cKocnNzBGYljLAByNLPoQ+BeF2hDPwuIDI
            zfRFewHP75CEhr/mdwbBZgJmoWrnE93gCG4lHGjFj028UmBllU+VrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-08T21:15:21Z"
    mac: ENC[AES256_GCM,data:Fyc+QQ79UuEzBOWw8cWaIIPk1CC4o1gh0wHhT5osiNqDnbg7htUMZDtQH9XrRGjkswe5IVLC7JkWmNeLjOH+UxznznzVnDe65Jy8DlzbUcFPn+BJjMzIkvtaBnfNX6oD8Z/2dOsowN68I+foo63DV0I4rwrxkpBDnauZ2oIecRk=,iv:GWHsZ3eMSmCoq1Jr4ayuTjz+CHhfPXgfxAKzPgyFV4E=,tag:aBS76ettocxSlf9h8m9z6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
