---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1h
  prune: true
  targetNamespace: cert-manager
  path: ./apps/cert-manager/cert-manager/app
  sourceRef:
    kind: GitRepository
    name: home-ops-iot
    namespace: flux-system

  decryption:
    provider: sops
    secretRef:
      name: sops-age
