---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  chartRef:
    kind: OCIRepository
    name: home-assistant
  interval: 1h

  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2025.10.1@sha256:c2febd5870a769d2131b2a716f3ed447289984e440ff415f3e634a6233101bb8
            env:
              TZ: Europe/Bucharest
              HASS_HTTP_TRUSTED_PROXY_1: 192.168.69.0/24
              HASS_HTTP_TRUSTED_PROXY_2: 10.42.0.0/16
            envFrom: []
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            appProtocol: kubernetes.io/ws
            port: 8123
    ingress:
      app:
        enabled: true
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host hass.home.mirceanton.com
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: home-assistant
                  port: 8123
        tls:
        - hosts:
          - *host
          secretName: hass-tls-cert

    persistence:
      config:
        existingClaim: home-assistant-config
        globalMounts: [ { path: /config } ]
      config-cache:
        existingClaim: home-assistant-cache
        globalMounts: [ { path: /config/.venv } ]
      tmpfs:
        type: emptyDir
        advancedMounts:
          home-assistant:
            app:
              - path: /config/logs
                subPath: logs
              - path: /config/tts
                subPath: tts
              - path: /tmp
                subPath: tmp
