---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: 4.13.3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx

  interval: 30m

  values:
    defaultBackend: { enabled: true }

    controller:
      kind: DaemonSet # run one pod per node
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      service:
        enabled: true
        type: ClusterIP

      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 200m
          memory: 200Mi
