---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1h
  prune: true
  wait: false
  targetNamespace: network
  path: ./apps/network/ingress-nginx/app
  sourceRef:
    kind: GitRepository
    name: home-ops-iot
    namespace: flux-system
