---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  wait: false
  targetNamespace: default
  path: ./apps/default/home-assistant/app
  sourceRef:
    kind: GitRepository
    name: home-ops-iot
    namespace: flux-system
